---
title: "Tasks Session 3"
author: "Tim Klingenberg"
date: "2024-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Combining the vectors into a data frame
stone_tools_data <- data.frame(
  inventory_number = c("LN15", "LN17", "LN18", "LN21", "LN23", "LN24"),
  blength = c(18, 14, 21, 14, 17, 16),
  breadth = c(9, 7, 10, 7, 8, 8),
  thickness = c(3, 2, 3, 3, 3, 2),
  material_type = c("chert", "chert", "obsidian", "chert", "obsidian", "obsidian"),
  material_provenance = c("local", "local", "local", "non-local", "local", "non-local")
)

# Display the data frame
knitr::kable(stone_tools_data)
```
```{r}
# Creating a csv-file
write.csv(stone_tools_data, "data/stone_tools_data.csv")
```

```{r}
# Reading/opening a csv-file
stone_tools_data2 <- read.csv("data/stone_tools_data.csv")[,-1]
```
```{r}
stone_tools_data$types_and_provenance <- paste(stone_tools_data$material_type,
                                               stone_tools_data$material_provenance,
                                               sep = " and ")
```

```{r}
stone_tools_data_table <- table(stone_tools_data$material_type)

png("plots/session3_barplot_material_type.png")

barplot(stone_tools_data_table,
        main ="Bar Plot of Count of artifacts by material type",
        xlab = "Material Type")

dev.off()
```
